version: "3.8"

services:
  db:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  
  backend:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./:/app
